import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { client } from '../lib/sanity';
import imageUrlBuilder from '@sanity/image-url';

const builder = imageUrlBuilder(client);

export default function Home({ products }) {
	console.log('products', products);
	console.log({ client });

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					{products.map((product) => {
						const { defaultProductVariant = {} } = product;
						const { images } = defaultProductVariant;
						return (
							<a href='#' key={product._id} className={styles.card}>
								<img src={builder.image(images[0]).width(300)} alt={product.title} />
								<h3>{product.title}</h3>
								<p>{product.blurb.en}</p>
							</a>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}

export async function getStaticProps() {
	// GROQ query; need to read more about it on Sanity's site
	const products = await client.fetch(`*[_type == "product"]`);

	return {
		props: {
			products
		}
	};
}
